const mongoose = require('mongoose');
const crewModel = require('../Model/mugiwaraModel')
mongoose.connect( "mongodb://127.0.0.1:27017/OnePiece", { useNewUrlParser: true });

// let CrewMembres = [ 
//   {
//     equipage: {
//       capitaine: {
//         nom: "Monkey D. Luffy",
//         fruit_du_demon: "Gomu Gomu no Mi",
//         armes: ["Aucune"],
//         age: 24,
//         taille: "1,72 m",
//         genre: "Homme",
//         ile_naissance: "East Blue",
//         reve: "Devenir le Roi des Pirates",
//         prime: "1,5 milliard de berrys",
//         affiliations: ["Pirates au Chapeau de Paille"],
//         image: "luffy.jpg",
//         poster_path: "/chemin/vers/jinbei.jpg",
//       },
//       premier_lieutenant: {
//         nom: "Roronoa Zoro",
//         armes: ["Wado Ichimonji", "Sandai Kitetsu", "Shusui"],
//         fruit_du_demon: "Aucun",
//         age: 28,
//         taille: "1,81 m",
//         genre: "Homme",
//         ile_naissance: "East Blue",
//         reve: "Devenir le meilleur épéiste du monde",
//         prime: "320 millions de berrys",
//         affiliations: ["Pirates au Chapeau de Paille"],
//         image: "zoro.jpg",
//         poster_path: "/chemin/vers/jinbei.jpg",
//       },
//       navigatrice: {
//         nom: "Nami",
//         armes: ["Sorcery Climat-Tact ", "Baguette Climatique"],
//         fruit_du_demon: "Aucun",
//         age: 22,
//         taille: "1,69 m",
//         genre: "Femme",
//         ile_naissance: "Cocoyasi",
//         reve: "Cartographier le monde entier",
//         prime: "66 millions de berrys",
//         affiliations: ["Pirates au Chapeau de Paille"],
//         image: "nami.jpg",
//         poster_path: "/chemin/vers/jinbei.jpg",
//       },
//       tireur_d_elite: {
//         nom: "Usopp",
//         armes: ["Fronde"],
//         fruit_du_demon: "Aucun",
//         age: 30,
//         taille: "1,74 m",
//         genre: "Homme",
//         ile_naissance: "Syrup",
//         reve: "Devenir un brave guerrier des mers",
//         prime: "300 millions de berrys",
//         affiliations: ["Pirates au Chapeau de Paille"],
//         image: "usopp.jpg",
//         poster_path: "/chemin/vers/jinbei.jpg",
//       },
//       chef: {
//         nom: "Sanji",
//         armes: ["Aucune"],
//         fruit_du_demon: "Aucun",
//         age: 29,
//         taille: "1,80 m",
//         genre: "Homme",
//         ile_naissance: "North Blue",
//         reve: "Trouver All Blue",
//         prime: "330 millions de berrys",
//         affiliations: ["Pirates au Chapeau de Paille"],
//         image: "sanji.jpg",
//         poster_path: "/chemin/vers/jinbei.jpg",
//       },
//       medecin: {
//         nom: "Chopper",
//         armes: ["Aucune"],
//         fruit_du_demon: "Hito Hito no Mi",
//         taille: "90 cm",
//         age: 17,
//         genre: "Homme",
//         ile_de_naissance: "Drum",
//         reve: "Devenir un grand médecin capable de soigner toutes les maladies",
//         prime: "1,000 Berrys",
//         affiliations: [
//           "Pirate du Chapeau de Paille",
//           "Équipage des Guerriers de la Mer",
//         ],
//         poster_path: "/chemin/vers/chopper.jpg",
//       },
//       archeologue: {
//         nom: "Robin",
//         armes: ["Aucune"],
//         fruit_du_demon: "Hana Hana no Mi",
//         taille: "188 cm",
//         age: 30,
//         genre: "Femme",
//         ile_de_naissance: "Ohara",
//         reve: "Découvrir la vérité sur le Siècle Oublié",
//         prime: "930,000,000 Berrys",
//         affiliations: [
//           "Pirate du Chapeau de Paille",
//           "Gouvernement Mondial (anciennement)",
//         ],
//         image: "sanji.jpg",
//         poster_path: "/chemin/vers/robin.jpg",
//       },
//       charpentier_naval: {
//         nom: "Franky",
//         armes: ["Sunny"],
//         fruit_du_demon: "Aucun",
//         taille: "240 cm",
//         age: 36,
//         genre: "Homme",
//         ile_de_naissance: "Water 7",
//         reve: "Construire un bateau capable de naviguer sur toutes les mers",
//         prime: "900,000,000 Berrys",
//         affiliations: [
//           "Pirate du Chapeau de Paille",
//           "Tom's Workers (anciennement)",
//         ],
//         image: "sanji.jpg",
//         poster_path: "/chemin/vers/franky.jpg",
//       },
//       musicien: {
//         nom: "Brook",
//         armes: ["Sabre"],
//         fruit_du_demon: "Yomi Yomi no Mi",
//         taille: "277 cm",
//         age: 90,
//         genre: "Homme",
//         ile_de_naissance: "West Blue",
//         reve: "Retrouver Laboon, la baleine qu'il a promis de revoir",
//         prime: "393,000,000 Berrys",
//         affiliations: [
//           "Pirate du Chapeau de Paille",
//           "Rumba Pirates (anciennement)",
//         ],
//         image: "sanji.jpg",
//         poster_path: "/chemin/vers/brook.jpg",
//       },
//       pilier: {
//         nom: "Jinbei",
//         taille: "301 cm",
//         armes: ["Aucun"],
//         fruit_du_demon: "Aucun",
//         age: 46,
//         genre: "Homme",
//         ile_de_naissance: "Fishman Island",
//         reve: "Créer une entente pacifique entre les humains et les poissons",
//         prime: "600,000,000 Berrys",
//         affiliations: [
//           "Pirate du Chapeau de Paille",
//           "Capitaine des Pirates du Soleil (anciennement)",
//         ],
//         image: "sanji.jpg",
//         poster_path: "/chemin/vers/jinbei.jpg",
//       },
//     },
//   },
// ];


let CrewMembres = [ 
    {
        nom: "Monkey D. Luffy",
        fruit_du_demon: "Gomu Gomu no Mi",
        armes: ["Aucun"],
        age: 24,
        taille: "1,72 m",
        genre: "Homme",
        ile_naissance: "East Blue",
        reve: "Devenir le Roi des Pirates",
        prime: "3 milliard de berrys",
        affiliations: ["Pirates au Chapeau de Paille"],
        image: "https://i.pinimg.com/originals/1f/7f/d2/1f7fd24f43efc419393c64990db819f7.jpg",
        poster_path: "https://images6.alphacoders.com/128/1286891.png",
        prime_poster : "https://i.pinimg.com/originals/9e/fd/c7/9efdc774b01fedff042dd90c96dd4895.jpg",
        slug:"luffy"
    },
    {
        nom: "Roronoa Zoro",
        armes: ["Wado Ichimonji", "Sandai Kitetsu", "Shusui"],
        fruit_du_demon: "Aucun",
        age: 28,
        taille: "1,81 m",
        genre: "Homme",
        ile_naissance: "East Blue",
        reve: "Devenir le meilleur épéiste du monde",
        prime: "1,111 milliard de berrys",
        affiliations: ["Pirates au Chapeau de Paille"],
        image: "https://i.pinimg.com/originals/80/4d/a1/804da11cd9023587ab6a4a5628ff78d1.jpg",
        poster_path: "https://i.pinimg.com/originals/82/13/38/8213383c39b881281a9979a70ca55046.jpg",
        prime_poster : "https://i.pinimg.com/originals/17/8f/41/178f41f15d210b6eb05d49164a75b560.jpg",
        slug:"zoro"
      },
      {
        nom: "Nami",
        armes: ["Sorcery Climat-Tact ", "Baguette Climatique"],
        fruit_du_demon: "Aucun",
        age: 22,
        taille: "1,69 m",
        genre: "Femme",
        ile_naissance: "Cocoyasi",
        reve: "Cartographier le monde entier",
        prime: "366 millions de berrys",
        affiliations: ["Pirates au Chapeau de Paille"],
        image: "https://i.pinimg.com/originals/eb/f9/d1/ebf9d12cf627e246435eefc9c93c336c.jpg",
        poster_path: "https://i.pinimg.com/originals/ad/b0/19/adb0194d48360ee289b1a0071faceb7b.jpg",
        prime_poster : "https://i.pinimg.com/originals/39/04/92/390492a72899cf32e2172784839ee670.jpg",
        slug:"nami"
      },
      {
        nom: "Usopp",
        armes: ["Fronde", "Kabuto Noir"],
        fruit_du_demon: "Aucun",
        age: 30,
        taille: "1,74 m",
        genre: "Homme",
        ile_naissance: "Syrup",
        reve: "Devenir un brave guerrier des mers",
        prime: "500 millions de berrys",
        affiliations: ["Pirates au Chapeau de Paille"],
        image: "https://i.pinimg.com/originals/ac/3b/90/ac3b90ffd6cccdba348ba518929083df.jpg",
        poster_path: "https://i.pinimg.com/originals/3b/ca/50/3bca500e4fb7bbdbde912f998d92b77b.jpg",
        prime_poster : "https://i.pinimg.com/originals/ec/3b/ea/ec3beada52663335713e4e1c9e7e6416.jpg",
        slug:"usopp"
      },
      {
        nom: "Sanji",
        armes: ["Aucune"],
        fruit_du_demon: "Aucun",
        age: 29,
        taille: "1,80 m",
        genre: "Homme",
        ile_naissance: "North Blue",
        reve: "Trouver All Blue",
        prime: "1, 032 milliard de berry",
        affiliations: ["Pirates au Chapeau de Paille"],
        image: "https://i.pinimg.com/originals/ef/4b/22/ef4b2250c712f4c191d742300763d548.jpg",
        poster_path: "https://i.pinimg.com/originals/f0/f0/f8/f0f0f8f7245a31ef407ef2e2491220e4.jpg",
        prime_poster : "https://i.pinimg.com/originals/87/24/f4/8724f42621190c452e7a7101b5f5e0fd.jpg",
        slug:"sanji"
      },
      {
        nom: "Chopper",
        armes: ["Aucune"],
        fruit_du_demon: "Hito Hito no Mi",
        taille: "90 cm",
        age: 17,
        genre: "Homme",
        ile_de_naissance: "Drum",
        reve: "Devenir un grand médecin capable de soigner toutes les maladies",
        prime: "1,000 Berrys",
        affiliations: [
          "Pirate du Chapeau de Paille",
          "Équipage des Guerriers de la Mer",
        ],
        image: "https://i.pinimg.com/originals/01/cb/93/01cb93670fc2a11d340925578111f507.jpg",
        poster_path : "https://images5.alphacoders.com/971/971570.jpg",
        prime_poster : "https://i.pinimg.com/originals/c9/ee/66/c9ee6640bcfc45420c096be02edb866c.jpg",
        slug:"chopper"
      },
      {
        nom: "Robin",
        armes: ["Aucune"],
        fruit_du_demon: "Hana Hana no Mi",
        taille: "188 cm",
        age: 30,
        genre: "Femme",
        ile_de_naissance: "Ohara",
        reve: "Découvrir la vérité sur le Siècle Oublié",
        prime: "930,000,000 Berrys",
        affiliations: [
          "Pirate du Chapeau de Paille",
          "Gouvernement Mondial (anciennement)",
        ],
        image: "https://i.pinimg.com/originals/f7/f0/c3/f7f0c3a27feca210f8b53edc33936ad8.jpg",
        poster_path : "https://images4.alphacoders.com/183/183418.jpg",
        prime_poster : "https://i.pinimg.com/originals/e3/8f/19/e38f19c8c1f548a675b9d9ec09f277aa.jpg",
        slug:"robin"
      },
      {
        nom: "Franky",
        armes: ["Sunny"],
        fruit_du_demon: "Aucun",
        taille: "240 cm",
        age: 36,
        genre: "Homme",
        ile_de_naissance: "Water 7",
        reve: "Construire un bateau capable de naviguer sur toutes les mers",
        prime: "394,000,000 Berrys",
        affiliations: [
          "Pirate du Chapeau de Paille",
          "Tom's Workers (anciennement)",
        ],
        image: "https://i.pinimg.com/originals/92/c4/17/92c417869e640fa16b979c30c6769fb7.jpg",
        poster_path: "https://wallpapercave.com/wp/wp7135409.jpg",
        prime_poster : "https://i.pinimg.com/originals/be/12/8e/be128ed2f6b00375abb1f991e53ad35e.jpg",
        slug:"franky"
      },
      {
        nom: "Brook",
        armes: ["Sabre"],
        fruit_du_demon: "Yomi Yomi no Mi",
        taille: "277 cm",
        age: 90,
        genre: "Homme",
        ile_de_naissance: "West Blue",
        reve: "Retrouver Laboon, la baleine qu'il a promis de revoir",
        prime: "383,000,000 Berrys",
        affiliations: [
          "Pirate du Chapeau de Paille",
          "Rumba Pirates (anciennement)",
        ],
        image: "https://i.pinimg.com/originals/a8/14/a4/a814a4ed560b75f568092b475c00ae4c.jpg",
        poster_path: "https://wallpapercave.com/wp/wp2156072.png",
        prime_poster : "https://i.pinimg.com/originals/19/54/9f/19549f98f77a69dda0483e135013c549.jpg",
        slug:"brook"
      },
      {
        nom: "Jinbei",
        taille: "301 cm",
        armes: ["Aucun"],
        fruit_du_demon: "Aucun",
        age: 46,
        genre: "Homme",
        ile_de_naissance: "Fishman Island",
        reve: "Créer une entente pacifique entre les humains et les poissons",
        prime: "1,100,000,000 millard Berrys",
        affiliations: [
          "Pirate du Chapeau de Paille",
          "Capitaine des Pirates du Soleil (anciennement)",
        ],
        image: "https://i.pinimg.com/originals/ae/07/34/ae0734a97603af3dfd73da6307aed3e8.jpg",
        poster_path: "https://wallpapercave.com/wp/wp3813525.png",
        prime_poster : "https://i.pinimg.com/originals/60/40/e5/6040e513506b03d6175ab664ec5cdc6e.jpg",
        slug:"jinbei"
      }
];



crewModel.insertMany(CrewMembres)
  .then(function(docs) {
    console.log('Multiple products inserted:', docs);
  })
  .catch(function(err) {
    console.error('Error inserting products:', err);
  });

